Support Ruby 2.7 arg syntax in callback_options
Fixes an issue in Ruby 2.7 and above where the callback options caused
a NoMethodError when using before_create.

```
\#<NoMethodError: undefined method `before_save' for {}:Hash

            target.send(method, *arguments, &block)
                  ^^^^^>
```